/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import locadora.ConectarDB;

/**
 *
 * @author Super i3
 */
public class Teste extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    boolean clicked1, clicked2, clicked3, clicked4;

    public Teste() {

        String numCarros_str = db.getLocadoraData("nCarros");
        String carrosAlugados_str = db.getLocadoraData("carrosAlugados");

        int carrosAlugados = Integer.valueOf(carrosAlugados_str);
        int numCarros = Integer.valueOf(numCarros_str);

        int p;
        try {
            p = ((carrosAlugados * 100) / numCarros);
        } catch (Exception e) {
            p = 0;
        }
        initComponents();
        falseAll();

        this.mudarCorBar(p);

        new Thread() {
            @Override
            public void run() {
                for (;;) {
                    dataEHora();

                    try {
                        sleep(1000);
                    } catch (InterruptedException ie) {
                        ie.printStackTrace();
                    }
                }
            }
        }.start();

        //Inicia o menu Geral 'clicado'
        menuGeral.setBackground(new Color(0x0073aa));
        txtMenuGeral.setForeground(new Color(0xffffff));
        clicked1 = true;
        conteudoGeral.setVisible(true);

        //DefaultTableModel model = (DefaultTableModel) tabelaCarros.getModel();
        //Object[] linha = new Object[4];
        // model.addRow(linha);
        atualizarListaCarros();
        atualizarListaClientes();
        //limparLista();
    }

    public void mudarCorBar(int porct) {
        int vermelho = (int) (2.55 * porct);
        int verde;

        Color cor;
        if (porct <= 25) {
            cor = new java.awt.Color(0x73ce0d);
        } else if (porct <= 50) {
            cor = new java.awt.Color(0X94a710);
        } else if (porct <= 75) {
            cor = new java.awt.Color(0xd75815);
        } else {
            cor = new java.awt.Color(0Xea4317);
        }

        // Color cor = new java.awt.Color(vermelho, verde, 0);
        alugadosBar.setForeground(cor);
    }

    public void limparLista(JTable tabela) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        if (model.getRowCount() > 0) {
            int tamanho = model.getRowCount();
            for (int i = 0; i <= tamanho - 1; i++) {
                model.removeRow(0);
            }
        }
    }

    public void atualizarListaCarros() {
        ConectarDB conn = new ConectarDB();
        DefaultTableModel model = (DefaultTableModel) tabelaCarros.getModel();
        Object[][] linha = conn.listaDeCarros();
        Object[] b = new Object[4];
        limparLista(tabelaCarros);
        if (linha.length > 0) {
            for (Object[] linha1 : linha) {
                System.arraycopy(linha1, 0, b, 0, 4);
                model.addRow(b);
            }
        }
    }

    public void atualizarListaClientes() {
        ConectarDB conn = new ConectarDB();
        DefaultTableModel model = (DefaultTableModel) tabelaClientes.getModel();
        Object[][] linha = conn.listaDeClientes();
        Object[] b = new Object[3];
        limparLista(tabelaClientes);
        if (linha.length > 0) {
            for (Object[] linha1 : linha) {
                System.arraycopy(linha1, 0, b, 0, 3);
                model.addRow(b);
            }
        }
    }

    public void dataEHora() {
        Calendar cal = new GregorianCalendar();
        String dia = addZero(cal.get(Calendar.DAY_OF_MONTH));
        String mes = addZero(cal.get(Calendar.MONTH) + 1);

        String ano = addZero(cal.get(Calendar.YEAR));

        String hora = addZero(cal.get(Calendar.HOUR));
        String minuto = addZero(cal.get(Calendar.MINUTE));
        String segundo = addZero(cal.get(Calendar.SECOND));

        txtData.setText(dia + "/" + mes + "/" + ano);
        txtHora.setText(hora + ":" + minuto + ":" + segundo);
    }

    public String addZero(int a) {
        String b = null;
        if (a <= 9) {
            b = "0" + a;
        } else {
            b = a + "";
        }
        return b;
    }

    ConectarDB db = new ConectarDB();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuPanel = new javax.swing.JPanel();
        menuGeral = new javax.swing.JPanel();
        txtMenuGeral = new javax.swing.JLabel();
        menuCarros = new javax.swing.JPanel();
        txtMenuCarros = new javax.swing.JLabel();
        menuClientes = new javax.swing.JPanel();
        txtMenuClientes = new javax.swing.JLabel();
        menuFuncionarios = new javax.swing.JPanel();
        txtMenuFuncionarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        conteudoGeral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        alugadosBar = new javax.swing.JProgressBar();
        porcentagemAlugados = new javax.swing.JLabel();
        receiveName = new javax.swing.JLabel();
        receiveNumCarros = new javax.swing.JLabel();
        receiveNumFuncionarios = new javax.swing.JLabel();
        receiveNumClientes = new javax.swing.JLabel();
        receiveNumAlugados = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        conteudoCarros = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCarros = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        conteudoClientes = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnNovoCliente = new javax.swing.JButton();
        btnAlugarCarro = new javax.swing.JButton();
        btnDevolverCarro = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        conteudoFuncionarios = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        menuFooter = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(db.getLocadoraData("nome"));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        menuPanel.setBackground(new java.awt.Color(35, 40, 44));
        menuPanel.setLayout(new java.awt.GridBagLayout());

        menuGeral.setBackground(new java.awt.Color(35, 40, 44));
        menuGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGeralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuGeralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuGeralMouseExited(evt);
            }
        });
        menuGeral.setLayout(new java.awt.GridBagLayout());

        txtMenuGeral.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuGeral.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuGeral.setText("Geral");
        txtMenuGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtMenuGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMenuGeralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMenuGeralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMenuGeralMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuGeral.add(txtMenuGeral, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        menuPanel.add(menuGeral, gridBagConstraints);

        menuCarros.setBackground(new java.awt.Color(35, 40, 44));
        menuCarros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCarrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCarrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuCarrosMouseExited(evt);
            }
        });
        menuCarros.setLayout(new java.awt.GridBagLayout());

        txtMenuCarros.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuCarros.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuCarros.setText("Carros");
        txtMenuCarros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuCarros.add(txtMenuCarros, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        menuPanel.add(menuCarros, gridBagConstraints);

        menuClientes.setBackground(new java.awt.Color(35, 40, 44));
        menuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuClientesMouseExited(evt);
            }
        });
        menuClientes.setLayout(new java.awt.GridBagLayout());

        txtMenuClientes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuClientes.setText("Clientes");
        txtMenuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuClientes.add(txtMenuClientes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        menuPanel.add(menuClientes, gridBagConstraints);

        menuFuncionarios.setBackground(new java.awt.Color(153, 153, 153));
        menuFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFuncionarios.setEnabled(false);
        menuFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseExited(evt);
            }
        });
        menuFuncionarios.setLayout(new java.awt.GridBagLayout());

        txtMenuFuncionarios.setBackground(new java.awt.Color(204, 204, 204));
        txtMenuFuncionarios.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuFuncionarios.setForeground(new java.awt.Color(102, 102, 102));
        txtMenuFuncionarios.setText("Funcionários");
        txtMenuFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuFuncionarios.add(txtMenuFuncionarios, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        menuPanel.add(menuFuncionarios, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 200;
        menuPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(menuPanel, gridBagConstraints);

        conteudoGeral.setBackground(new java.awt.Color(241, 241, 241));
        conteudoGeral.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                conteudoGeralComponentShown(evt);
            }
        });
        conteudoGeral.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Geral");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Carros alugados:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nº de carros:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Nº de funcionários:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Clientes registrados:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Nome:");

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("Frota");

        alugadosBar.setForeground(new java.awt.Color(255, 102, 102));
        alugadosBar.setValue(30);
        String numCarros_str = db.getLocadoraData("nCarros");
        String carrosAlugados_str = db.getLocadoraData("carrosAlugados");

        int carrosAlugados = Integer.valueOf(carrosAlugados_str);
        int numCarros = Integer.valueOf(numCarros_str);

        int p;

        try {
            p = ((carrosAlugados*100)/numCarros);
        } catch (Exception e){
            p = 0;
        }
        alugadosBar.setValue(p);

        porcentagemAlugados.setText("30% alugados");
        porcentagemAlugados.setText(p + "% alugados");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(porcentagemAlugados))
                    .addComponent(alugadosBar, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(porcentagemAlugados)
                        .addGap(3, 3, 3)))
                .addComponent(alugadosBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        receiveName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiveName.setText("Null");
        receiveName.setText(db.getLocadoraData("nome"));

        receiveNumCarros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiveNumCarros.setText("Null");
        receiveNumCarros.setText(db.getLocadoraData("nCarros"));

        receiveNumFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiveNumFuncionarios.setForeground(new java.awt.Color(153, 153, 153));
        receiveNumFuncionarios.setText("Null");
        receiveNumFuncionarios.setText(db.getLocadoraData("nFuncionarios"));

        receiveNumClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiveNumClientes.setText("Null");
        receiveNumClientes.setText(db.getLocadoraData("nClientes"));

        receiveNumAlugados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiveNumAlugados.setText("Null");
        receiveNumAlugados.setText(db.getLocadoraData("carrosAlugados"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiveNumAlugados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiveName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiveNumClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiveNumFuncionarios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiveNumCarros))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(receiveName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(receiveNumCarros))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(receiveNumFuncionarios))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(receiveNumClientes))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(receiveNumAlugados))
                .addGap(72, 72, 72)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtData.setText("Data");

        txtHora.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHora, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(78, 78, 78))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(txtData)
                            .addGap(15, 15, 15))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(txtHora))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoGeral.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoGeral, gridBagConstraints);

        conteudoCarros.setBackground(new java.awt.Color(241, 241, 241));
        conteudoCarros.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                conteudoCarrosComponentShown(evt);
            }
        });
        conteudoCarros.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Carros");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Novo carro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCarros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaCarros);
        if (tabelaCarros.getColumnModel().getColumnCount() > 0) {
            tabelaCarros.getColumnModel().getColumn(0).setResizable(false);
            tabelaCarros.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabelaCarros.getColumnModel().getColumn(1).setResizable(false);
            tabelaCarros.getColumnModel().getColumn(2).setResizable(false);
            tabelaCarros.getColumnModel().getColumn(3).setResizable(false);
        }
        tabelaCarros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jButton2.setText("Procurar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover carro");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoCarros.add(jPanel3);
        jPanel3.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoCarros, gridBagConstraints);

        conteudoClientes.setBackground(new java.awt.Color(241, 241, 241));
        conteudoClientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                conteudoClientesComponentShown(evt);
            }
        });
        conteudoClientes.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(241, 241, 241));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Clientes");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Alugando"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaClientes);
        if (tabelaClientes.getColumnModel().getColumnCount() > 0) {
            tabelaClientes.getColumnModel().getColumn(0).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(1).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(2).setResizable(false);
        }
        tabelaClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        btnNovoCliente.setText("Novo cliente");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnAlugarCarro.setText("Alugar carro");
        btnAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugarCarroActionPerformed(evt);
            }
        });

        btnDevolverCarro.setText("Devolver carro");
        btnDevolverCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverCarroActionPerformed(evt);
            }
        });

        jButton4.setText("Procurar");
        jButton4.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnNovoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlugarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDevolverCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCliente)
                    .addComponent(btnAlugarCarro)
                    .addComponent(btnDevolverCarro)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conteudoClientes.add(jPanel5);
        jPanel5.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoClientes, gridBagConstraints);

        conteudoFuncionarios.setBackground(new java.awt.Color(241, 241, 241));
        conteudoFuncionarios.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(241, 241, 241));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Funcionários");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conteudoFuncionarios.add(jPanel7);
        jPanel7.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoFuncionarios, gridBagConstraints);

        menuFooter.setBackground(new java.awt.Color(58, 58, 58));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Desenvolvido por:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lavyk Soares");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Andécio Araujo");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Medson Lucius");

        javax.swing.GroupLayout menuFooterLayout = new javax.swing.GroupLayout(menuFooter);
        menuFooter.setLayout(menuFooterLayout);
        menuFooterLayout.setHorizontalGroup(
            menuFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFooterLayout.createSequentialGroup()
                .addGroup(menuFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuFooterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(menuFooterLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(menuFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))))
                .addContainerGap())
        );
        menuFooterLayout.setVerticalGroup(
            menuFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        getContentPane().add(menuFooter, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarrosMouseEntered
        if (!clicked2) {
            menuCarros.setBackground(new Color(25, 30, 35));
            txtMenuCarros.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuCarrosMouseEntered

    private void menuCarrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarrosMouseExited
        if (!clicked2) {
            menuCarros.setBackground(new Color(0x23282d));
            txtMenuCarros.setForeground(new Color(0xffffff));
        }

    }//GEN-LAST:event_menuCarrosMouseExited

    private void menuClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseEntered
        if (!clicked3) {
            menuClientes.setBackground(new Color(25, 30, 35));
            txtMenuClientes.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuClientesMouseEntered

    private void menuClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseExited
        if (!clicked3) {
            menuClientes.setBackground(new Color(0x23282d));
            txtMenuClientes.setForeground(new Color(0xffffff));
        }
    }//GEN-LAST:event_menuClientesMouseExited

    private void menuCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarrosMouseClicked
        falseAll();
        menuCarros.setBackground(new Color(0x0073aa));
        txtMenuCarros.setForeground(new Color(0xffffff));
        clicked2 = true;
        conteudoCarros.setVisible(true);
    }//GEN-LAST:event_menuCarrosMouseClicked

    private void menuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseClicked
        falseAll();
        menuClientes.setBackground(new Color(0x0073aa));
        txtMenuClientes.setForeground(new Color(0xffffff));
        clicked3 = true;
        conteudoClientes.setVisible(true);
    }//GEN-LAST:event_menuClientesMouseClicked

    private void menuGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGeralMouseClicked
        falseAll();
        menuGeral.setBackground(new Color(0x0073aa));
        txtMenuGeral.setForeground(new Color(0xffffff));
        clicked1 = true;
        conteudoGeral.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_menuGeralMouseClicked

    private void menuGeralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGeralMouseEntered
        if (!clicked1) {
            menuGeral.setBackground(new Color(25, 30, 35));
            txtMenuGeral.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuGeralMouseEntered

    private void menuGeralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGeralMouseExited
        if (!clicked1) {
            menuGeral.setBackground(new Color(0x23282d));
            txtMenuGeral.setForeground(new Color(0xffffff));
        }
    }//GEN-LAST:event_menuGeralMouseExited

    private void txtMenuGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuGeralMouseClicked
        falseAll();
        menuGeral.setBackground(new Color(0x0073aa));
        txtMenuGeral.setForeground(new Color(0xffffff));
        clicked1 = true;
        conteudoGeral.setVisible(true);
    }//GEN-LAST:event_txtMenuGeralMouseClicked

    private void txtMenuGeralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuGeralMouseEntered
        if (!clicked1) {
            menuGeral.setBackground(new Color(25, 30, 35));
            txtMenuGeral.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_txtMenuGeralMouseEntered

    private void txtMenuGeralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuGeralMouseExited
        if (!clicked1) {
            menuGeral.setBackground(new Color(0x23282d));
            txtMenuGeral.setForeground(new Color(0xffffff));
        }
    }//GEN-LAST:event_txtMenuGeralMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CriarCarro().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void conteudoGeralComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_conteudoGeralComponentShown
        //JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");
        ConectarDB conn = new ConectarDB();
        receiveNumCarros.setText(conn.getLocadoraData("nCarros"));
        receiveNumFuncionarios.setText(conn.getLocadoraData("nFuncionarios"));
        receiveNumClientes.setText(conn.getLocadoraData("nClientes"));
        receiveNumAlugados.setText(conn.getLocadoraData("carrosAlugados"));

        String numCarros_str = db.getLocadoraData("nCarros");
        String carrosAlugados_str = db.getLocadoraData("carrosAlugados");

        int carrosAlugados = Integer.valueOf(carrosAlugados_str);
        int numCarros = Integer.valueOf(numCarros_str);

        int p;
        try {
            p = ((carrosAlugados * 100) / numCarros);
        } catch (Exception e) {
            p = 0;
        }

        this.mudarCorBar(p);
        alugadosBar.setValue(p);
        porcentagemAlugados.setText(p + "% alugados");
    }//GEN-LAST:event_conteudoGeralComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        atualizarListaCarros();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        atualizarListaCarros();
        atualizarListaClientes();
    }//GEN-LAST:event_formFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int carro = tabelaCarros.getSelectedRow();
        String placa = tabelaCarros.getValueAt(carro, 0).toString();
        System.out.println(placa);
        ConectarDB conn = new ConectarDB();
        conn.delete("Carros", "placa", placa);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menuFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseExited
        /*
        if (!clicked4) {
            menuFuncionarios.setBackground(new Color(0x23282d));
            txtMenuFuncionarios.setForeground(new Color(0xffffff));
        }
         */
    }//GEN-LAST:event_menuFuncionariosMouseExited

    private void menuFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseEntered
        /*
        if (!clicked4) {
            menuFuncionarios.setBackground(new Color(25, 30, 35));
            txtMenuFuncionarios.setForeground(new Color(0x00b9eb));
        }
         */
    }//GEN-LAST:event_menuFuncionariosMouseEntered

    private void menuFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseClicked
        /*
        falseAll();
        menuFuncionarios.setBackground(new Color(0x0073aa));
        txtMenuFuncionarios.setForeground(new Color(0xffffff));
        clicked4 = true;
        conteudoFuncionarios.setVisible(true);
         */
    }//GEN-LAST:event_menuFuncionariosMouseClicked

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        new CriarCliente().setVisible(true);
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnDevolverCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverCarroActionPerformed
        int cliente = tabelaClientes.getSelectedRow();

        if (cliente != -1) {
            DefaultTableModel tabelaClientesModel = (DefaultTableModel) tabelaClientes.getModel();
            String alugando = tabelaClientesModel.getValueAt(cliente, 2).toString();
            String clienteNome = tabelaClientesModel.getValueAt(cliente, 0).toString();
            if (alugando.equals("null")) {
                JOptionPane.showMessageDialog(null, clienteNome + " não está com um carro alugado. \nSelecione outro cliente!");
            } else {
                new ConectarDB().setCarroAlugando(clienteNome, alugando, false);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente!");
        }
    }//GEN-LAST:event_btnDevolverCarroActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.atualizarListaCarros();
        this.atualizarListaClientes();
    }//GEN-LAST:event_formWindowGainedFocus

    private void conteudoCarrosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_conteudoCarrosComponentShown
        this.atualizarListaCarros();
    }//GEN-LAST:event_conteudoCarrosComponentShown

    private void conteudoClientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_conteudoClientesComponentShown
        this.atualizarListaClientes();
    }//GEN-LAST:event_conteudoClientesComponentShown

    private void btnAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugarCarroActionPerformed
        int cliente = tabelaClientes.getSelectedRow();

        if (cliente != -1) {
            DefaultTableModel tabelaClientesModel = (DefaultTableModel) tabelaClientes.getModel();
            String alugando = tabelaClientesModel.getValueAt(cliente, 2).toString();
            String clienteNome = tabelaClientesModel.getValueAt(cliente, 0).toString();
            if (!alugando.equals("null")) {
                JOptionPane.showMessageDialog(null, clienteNome + " já está com um carro alugado.\nSelecione outro cliente!");
            } else {
                String clienteCPF = tabelaClientesModel.getValueAt(cliente, 1).toString();
                AlugarCarro alugarCarro = new AlugarCarro();
                alugarCarro.setNome(clienteNome);
                alugarCarro.setCPF(clienteCPF);
                alugarCarro.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente!");
        }
    }//GEN-LAST:event_btnAlugarCarroActionPerformed

    public void falseAll() {
        menuGeral.setBackground(new Color(0x23282d));
        txtMenuGeral.setForeground(new Color(0xffffff));

        menuCarros.setBackground(new Color(0x23282d));
        txtMenuCarros.setForeground(new Color(0xffffff));

        menuClientes.setBackground(new Color(0x23282d));
        txtMenuClientes.setForeground(new Color(0xffffff));

        // menuFuncionarios.setBackground(new Color(0x23282d));
        // txtMenuFuncionarios.setForeground(new Color(0xffffff));
        conteudoGeral.setVisible(false);
        conteudoCarros.setVisible(false);
        conteudoClientes.setVisible(false);
        conteudoFuncionarios.setVisible(false);
        clicked1 = false;
        clicked2 = false;
        clicked3 = false;
        clicked4 = false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar alugadosBar;
    private javax.swing.JButton btnAlugarCarro;
    private javax.swing.JButton btnDevolverCarro;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JPanel conteudoCarros;
    private javax.swing.JPanel conteudoClientes;
    private javax.swing.JPanel conteudoFuncionarios;
    private javax.swing.JPanel conteudoGeral;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menuCarros;
    private javax.swing.JPanel menuClientes;
    private javax.swing.JPanel menuFooter;
    private javax.swing.JPanel menuFuncionarios;
    private javax.swing.JPanel menuGeral;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel porcentagemAlugados;
    private javax.swing.JLabel receiveName;
    private javax.swing.JLabel receiveNumAlugados;
    private javax.swing.JLabel receiveNumCarros;
    private javax.swing.JLabel receiveNumClientes;
    private javax.swing.JLabel receiveNumFuncionarios;
    private javax.swing.JTable tabelaCarros;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtMenuCarros;
    private javax.swing.JLabel txtMenuClientes;
    private javax.swing.JLabel txtMenuFuncionarios;
    private javax.swing.JLabel txtMenuGeral;
    // End of variables declaration//GEN-END:variables
}
