/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Super i3
 */
public class Teste extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    boolean clicked1, clicked2, clicked3, clicked4;

    public Teste() {
        initComponents();

        new Thread() {
            @Override
            public void run() {
                for (;;) {
                    dataEHora();

                    try {
                        sleep(1000);
                    } catch (InterruptedException ie) {
                        ie.printStackTrace();
                    }
                }
            }
        }.start();

    }

    public void dataEHora() {
        Calendar cal = new GregorianCalendar();
        String dia = addZero(cal.get(Calendar.DAY_OF_MONTH));
        String mes = addZero(cal.get(Calendar.MONTH) + 1);

        String ano = addZero(cal.get(Calendar.YEAR));

        String hora = addZero(cal.get(Calendar.HOUR));
        String minuto = addZero(cal.get(Calendar.MINUTE));
        String segundo = addZero(cal.get(Calendar.SECOND));

        txtData.setText(dia + "/" + mes + "/" + ano);
        txtHora.setText(hora + ":" + minuto + ":" + segundo);
    }

    public String addZero(int a) {
        String b = null;
        if (a <= 9) {
            b = "0" + a;
        } else {
            b = a + "";
        }
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuPanel = new javax.swing.JPanel();
        menuGeral = new javax.swing.JPanel();
        txtMenuGeral = new javax.swing.JLabel();
        menuCarros = new javax.swing.JPanel();
        txtMenuCarros = new javax.swing.JLabel();
        menuClientes = new javax.swing.JPanel();
        txtMenuClientes = new javax.swing.JLabel();
        menuFuncionarios = new javax.swing.JPanel();
        txtMenuFuncionarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        conteudoGeral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtData = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        conteudoCarros = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        conteudoClientes = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        conteudoFuncionarios = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        menuFooter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locadora");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        menuPanel.setBackground(new java.awt.Color(35, 40, 44));
        menuPanel.setLayout(new java.awt.GridBagLayout());

        menuGeral.setBackground(new java.awt.Color(35, 40, 44));
        menuGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGeralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuGeralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuGeralMouseExited(evt);
            }
        });
        menuGeral.setLayout(new java.awt.GridBagLayout());

        txtMenuGeral.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuGeral.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuGeral.setText("Geral");
        txtMenuGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtMenuGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMenuGeralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMenuGeralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMenuGeralMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuGeral.add(txtMenuGeral, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        menuPanel.add(menuGeral, gridBagConstraints);

        menuCarros.setBackground(new java.awt.Color(35, 40, 44));
        menuCarros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCarrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCarrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuCarrosMouseExited(evt);
            }
        });
        menuCarros.setLayout(new java.awt.GridBagLayout());

        txtMenuCarros.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuCarros.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuCarros.setText("Carros");
        txtMenuCarros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuCarros.add(txtMenuCarros, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        menuPanel.add(menuCarros, gridBagConstraints);

        menuClientes.setBackground(new java.awt.Color(35, 40, 44));
        menuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuClientesMouseExited(evt);
            }
        });
        menuClientes.setLayout(new java.awt.GridBagLayout());

        txtMenuClientes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuClientes.setText("Clientes");
        txtMenuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuClientes.add(txtMenuClientes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        menuPanel.add(menuClientes, gridBagConstraints);

        menuFuncionarios.setBackground(new java.awt.Color(35, 40, 44));
        menuFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseExited(evt);
            }
        });
        menuFuncionarios.setLayout(new java.awt.GridBagLayout());

        txtMenuFuncionarios.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtMenuFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuFuncionarios.setText("Funcionários");
        txtMenuFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        menuFuncionarios.add(txtMenuFuncionarios, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        menuPanel.add(menuFuncionarios, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 200;
        menuPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(menuPanel, gridBagConstraints);

        conteudoGeral.setBackground(new java.awt.Color(241, 241, 241));
        conteudoGeral.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Geral");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Carros alugados:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nº de carros:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Nº de funcionários:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Clientes registrados:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Nome:");

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtData.setText("Data");

        txtHora.setText("jLabel11");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHora, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(179, 179, 179))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHora)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoGeral.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoGeral, gridBagConstraints);

        conteudoCarros.setBackground(new java.awt.Color(241, 241, 241));
        conteudoCarros.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Carros");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoCarros.add(jPanel3);
        jPanel3.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoCarros, gridBagConstraints);

        conteudoClientes.setBackground(new java.awt.Color(241, 241, 241));
        conteudoClientes.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(241, 241, 241));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Clientes");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoClientes.add(jPanel5);
        jPanel5.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoClientes, gridBagConstraints);

        conteudoFuncionarios.setBackground(new java.awt.Color(241, 241, 241));
        conteudoFuncionarios.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(241, 241, 241));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Funcionários");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoFuncionarios.add(jPanel7);
        jPanel7.setBounds(0, 0, 500, 460);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 300;
        getContentPane().add(conteudoFuncionarios, gridBagConstraints);

        menuFooter.setBackground(new java.awt.Color(58, 58, 58));

        javax.swing.GroupLayout menuFooterLayout = new javax.swing.GroupLayout(menuFooter);
        menuFooter.setLayout(menuFooterLayout);
        menuFooterLayout.setHorizontalGroup(
            menuFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menuFooterLayout.setVerticalGroup(
            menuFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 80;
        getContentPane().add(menuFooter, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarrosMouseEntered
        if (!clicked2) {
            menuCarros.setBackground(new Color(25, 30, 35));
            txtMenuCarros.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuCarrosMouseEntered

    private void menuCarrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarrosMouseExited
        if (!clicked2) {
            menuCarros.setBackground(new Color(0x23282d));
            txtMenuCarros.setForeground(new Color(0xffffff));
        }

    }//GEN-LAST:event_menuCarrosMouseExited

    private void menuClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseEntered
        if (!clicked3) {
            menuClientes.setBackground(new Color(25, 30, 35));
            txtMenuClientes.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuClientesMouseEntered

    private void menuClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseExited
        if (!clicked3) {
            menuClientes.setBackground(new Color(0x23282d));
            txtMenuClientes.setForeground(new Color(0xffffff));
        }
    }//GEN-LAST:event_menuClientesMouseExited

    private void menuCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarrosMouseClicked
        falseAll();
        menuCarros.setBackground(new Color(0x0073aa));
        txtMenuCarros.setForeground(new Color(0xffffff));
        clicked2 = true;
        conteudoCarros.setVisible(true);
    }//GEN-LAST:event_menuCarrosMouseClicked

    private void menuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseClicked
        falseAll();
        menuClientes.setBackground(new Color(0x0073aa));
        txtMenuClientes.setForeground(new Color(0xffffff));
        clicked3 = true;
        conteudoClientes.setVisible(true);
    }//GEN-LAST:event_menuClientesMouseClicked

    private void menuFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseClicked
        falseAll();
        menuFuncionarios.setBackground(new Color(0x0073aa));
        txtMenuFuncionarios.setForeground(new Color(0xffffff));
        clicked4 = true;
        conteudoFuncionarios.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosMouseClicked

    private void menuFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseEntered
        if (!clicked4) {
            menuFuncionarios.setBackground(new Color(25, 30, 35));
            txtMenuFuncionarios.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuFuncionariosMouseEntered

    private void menuFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseExited
        if (!clicked4) {
            menuFuncionarios.setBackground(new Color(0x23282d));
            txtMenuFuncionarios.setForeground(new Color(0xffffff));
        }// TODO add your handling code here:
    }//GEN-LAST:event_menuFuncionariosMouseExited

    private void menuGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGeralMouseClicked
        falseAll();
        menuGeral.setBackground(new Color(0x0073aa));
        txtMenuGeral.setForeground(new Color(0xffffff));
        clicked1 = true;
        conteudoGeral.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_menuGeralMouseClicked

    private void menuGeralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGeralMouseEntered
        if (!clicked1) {
            menuGeral.setBackground(new Color(25, 30, 35));
            txtMenuGeral.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_menuGeralMouseEntered

    private void menuGeralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGeralMouseExited
        if (!clicked1) {
            menuGeral.setBackground(new Color(0x23282d));
            txtMenuGeral.setForeground(new Color(0xffffff));
        }
    }//GEN-LAST:event_menuGeralMouseExited

    private void txtMenuGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuGeralMouseClicked
        falseAll();
        menuGeral.setBackground(new Color(0x0073aa));
        txtMenuGeral.setForeground(new Color(0xffffff));
        clicked1 = true;
        conteudoGeral.setVisible(true);
    }//GEN-LAST:event_txtMenuGeralMouseClicked

    private void txtMenuGeralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuGeralMouseEntered
        if (!clicked1) {
            menuGeral.setBackground(new Color(25, 30, 35));
            txtMenuGeral.setForeground(new Color(0x00b9eb));
        }
    }//GEN-LAST:event_txtMenuGeralMouseEntered

    private void txtMenuGeralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuGeralMouseExited
        if (!clicked1) {
            menuGeral.setBackground(new Color(0x23282d));
            txtMenuGeral.setForeground(new Color(0xffffff));
        }
    }//GEN-LAST:event_txtMenuGeralMouseExited

    public void falseAll() {
        menuGeral.setBackground(new Color(0x23282d));
        txtMenuGeral.setForeground(new Color(0xffffff));

        menuCarros.setBackground(new Color(0x23282d));
        txtMenuCarros.setForeground(new Color(0xffffff));

        menuClientes.setBackground(new Color(0x23282d));
        txtMenuClientes.setForeground(new Color(0xffffff));

        menuFuncionarios.setBackground(new Color(0x23282d));
        txtMenuFuncionarios.setForeground(new Color(0xffffff));

        conteudoGeral.setVisible(false);
        conteudoCarros.setVisible(false);
        conteudoClientes.setVisible(false);
        conteudoFuncionarios.setVisible(false);
        clicked1 = false;
        clicked2 = false;
        clicked3 = false;
        clicked4 = false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conteudoCarros;
    private javax.swing.JPanel conteudoClientes;
    private javax.swing.JPanel conteudoFuncionarios;
    private javax.swing.JPanel conteudoGeral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel menuCarros;
    private javax.swing.JPanel menuClientes;
    private javax.swing.JPanel menuFooter;
    private javax.swing.JPanel menuFuncionarios;
    private javax.swing.JPanel menuGeral;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtMenuCarros;
    private javax.swing.JLabel txtMenuClientes;
    private javax.swing.JLabel txtMenuFuncionarios;
    private javax.swing.JLabel txtMenuGeral;
    // End of variables declaration//GEN-END:variables
}
